/*
 * This file is generated by jOOQ.
 */
package org.avijayan.jooqgenerated.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.avijayan.jooqgenerated.tables.OrphanedBlockCandidates;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrphanedBlockCandidatesRecord extends UpdatableRecordImpl<OrphanedBlockCandidatesRecord> implements Record4<Integer, Timestamp, Long, Long> {

    private static final long serialVersionUID = -408887821;

    /**
     * Setter for <code>orphaned_block_candidates.run_id</code>.
     */
    public void setRunId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orphaned_block_candidates.run_id</code>.
     */
    public Integer getRunId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orphaned_block_candidates.run_timestamp</code>.
     */
    public void setRunTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>orphaned_block_candidates.run_timestamp</code>.
     */
    public Timestamp getRunTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>orphaned_block_candidates.container_id</code>.
     */
    public void setContainerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>orphaned_block_candidates.container_id</code>.
     */
    public Long getContainerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>orphaned_block_candidates.local_id</code>.
     */
    public void setLocalId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>orphaned_block_candidates.local_id</code>.
     */
    public Long getLocalId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES.RUN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES.RUN_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES.CONTAINER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES.LOCAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getRunTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getContainerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getLocalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getRunTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getContainerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLocalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrphanedBlockCandidatesRecord value1(Integer value) {
        setRunId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrphanedBlockCandidatesRecord value2(Timestamp value) {
        setRunTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrphanedBlockCandidatesRecord value3(Long value) {
        setContainerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrphanedBlockCandidatesRecord value4(Long value) {
        setLocalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrphanedBlockCandidatesRecord values(Integer value1, Timestamp value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrphanedBlockCandidatesRecord
     */
    public OrphanedBlockCandidatesRecord() {
        super(OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES);
    }

    /**
     * Create a detached, initialised OrphanedBlockCandidatesRecord
     */
    public OrphanedBlockCandidatesRecord(Integer runId, Timestamp runTimestamp, Long containerId, Long localId) {
        super(OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES);

        set(0, runId);
        set(1, runTimestamp);
        set(2, containerId);
        set(3, localId);
    }
}
