/*
 * This file is generated by jOOQ.
 */
package org.avijayan.jooqgenerated;


import javax.annotation.Generated;

import org.avijayan.jooqgenerated.tables.OrphanedBlockCandidates;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_ORPHANED_BLOCK_CANDIDATES_1 = Indexes0.SQLITE_AUTOINDEX_ORPHANED_BLOCK_CANDIDATES_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SQLITE_AUTOINDEX_ORPHANED_BLOCK_CANDIDATES_1 = Internal.createIndex("sqlite_autoindex_orphaned_block_candidates_1", OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES, new OrderField[] { OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES.RUN_ID }, true);
    }
}
