/*
 * This file is generated by jOOQ.
 */
package org.avijayan.jooqgenerated;


import javax.annotation.Generated;

import org.avijayan.jooqgenerated.tables.OrphanedBlockCandidates;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orphaned_block_candidates</code>.
     */
    public static final OrphanedBlockCandidates ORPHANED_BLOCK_CANDIDATES = org.avijayan.jooqgenerated.tables.OrphanedBlockCandidates.ORPHANED_BLOCK_CANDIDATES;
}
